{"id":"event-1754155080515-memzaav38","timestamp":"2025-08-02T17:18:00.515Z","sessionId":"system","eventType":"error_occurred","source":"error-handler","severity":"medium","message":"error_occurred: error-handler","data":{"errorId":"error-1754155080514-l5g355","severity":"medium","category":"validation","source":"test-component","message":"Test validation error","recoverable":true,"retryable":false,"stackTrace":["Error: Test validation error","    at Object.<anonymous> (C:\\Users\\gabri\\Documents\\Infotopology\\Phoenix\\phoenix-code-lite\\tests\\integration\\phase-1-basic.test.ts:99:11)","    at Promise.finally.completed (C:\\Users\\gabri\\Documents\\Infotopology\\Phoenix\\phoenix-code-lite\\node_modules\\jest-circus\\build\\jestAdapterInit.js:1559:28)","    at new Promise (<anonymous>)","    at callAsyncCircusFn (C:\\Users\\gabri\\Documents\\Infotopology\\Phoenix\\phoenix-code-lite\\node_modules\\jest-circus\\build\\jestAdapterInit.js:1499:10)","    at _callCircusTest (C:\\Users\\gabri\\Documents\\Infotopology\\Phoenix\\phoenix-code-lite\\node_modules\\jest-circus\\build\\jestAdapterInit.js:1009:40)","    at _runTest (C:\\Users\\gabri\\Documents\\Infotopology\\Phoenix\\phoenix-code-lite\\node_modules\\jest-circus\\build\\jestAdapterInit.js:949:3)","    at _runTestsForDescribeBlock (C:\\Users\\gabri\\Documents\\Infotopology\\Phoenix\\phoenix-code-lite\\node_modules\\jest-circus\\build\\jestAdapterInit.js:839:13)","    at _runTestsForDescribeBlock (C:\\Users\\gabri\\Documents\\Infotopology\\Phoenix\\phoenix-code-lite\\node_modules\\jest-circus\\build\\jestAdapterInit.js:829:11)","    at _runTestsForDescribeBlock (C:\\Users\\gabri\\Documents\\Infotopology\\Phoenix\\phoenix-code-lite\\node_modules\\jest-circus\\build\\jestAdapterInit.js:829:11)"]}}
{"id":"event-1754155080515-g3i264sgi","timestamp":"2025-08-02T17:18:00.515Z","sessionId":"system","eventType":"error_handled","source":"error-handler","severity":"medium","message":"error_handled: error-handler","data":{"errorId":"error-1754155080514-l5g355","handled":true,"recovered":false,"action":"validation_failed","message":"Validation error: Test validation error","retry":false}}
